### ISSUE TITLE
js directory needs to be created in custom_react example

### ISSUE THREAD

**Issue by tzuni** [stitchfix/pyxley#2]
Hi! I'm excitedly working through some of the examples and I ran into the issue below:

```
$python app.py

Traceback (most recent call last):
  File "app.py", line 47, in <module>
    transformer.transform(f,js_path=jsx_output+f.split('/')[-1])
  File "/usr/local/lib/python2.7/dist-packages/react/jsx.py", line 53, in transform
    with open(js_path, 'wb') as o:
IOError: [Errno 2] No such file or directory: 'static/js/custom.js'
```

Upon cloning only the static/jsx directory exists and creating the static/js directory fixes things though.

**Comment by nmkridler** [comment]
Thanks for catching this! I'll add it in.

**Comment by golangninja** [comment]
I also just now received a similar error:

Traceback (most recent call last):
  File "app.py", line 47, in <module>
    transformer.transform(f,js_path=jsx_output+f.split('/')[-1])
  File "C:\Python27\lib\site-packages\react\jsx.py", line 53, in transform
    with open(js_path, 'wb') as o:
IOError: [Errno 2] No such file or directory: 'static/js/jsx\\custom.js'

I fixed it by copying the /jsx folder within /js.
