### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by hpsilva** [stitchfix/pyxley#36]
Hi there,

I just came across this library and was wondering whether it is able to deal with tabs and side bar alike menu? Is there any way to render them directly thru pyxley ?

Looked to the source code but did not found any hints 

Best regards

**Comment by nmkridler** [comment]
It's possible, but you have to create your own custom layout component in React. There's an example in the examples/custom_react folder. 
In [app.py](https://github.com/stitchfix/pyxley/blob/master/examples/custom_react/project/app.py) on line 31 where the UI component is created:
```python
ui = UILayout(
    "RunLayout",
    "./jsx/custom",
    "component_id")
```
`RunLayout` is a React component that lives in `./jsx/custom.js`. So if you wanted to add tabs or other layout things, you could do it there.

**Comment by hpsilva** [comment]
Got it.
Will have a look at it

Cheers!
