### ISSUE TITLE
ImportError: cannot import name 'jsx'

### ISSUE THREAD

**Issue by phillipc09** [stitchfix/pyxley#37]
Hi, I'm VERY new to python but have fallen in love w/ pandas.  As such I'm trying to use pyxley for some of my projects.  Quick question....when I run the datatables example, and set up bower, I get an error b/c the example doesn't have a bower file.  If I borrow bower.json from another folder, when I run the app.py, I get an import error, " cannot import name 'jsx'"  

What am I doing wrong?

**Comment by nmkridler** [comment]
I forgot to update the readme in that folder. Follow the set up in one of the other examples. 
Like [metricsgraphics](https://github.com/stitchfix/pyxley/tree/master/examples/metricsgraphics).

**Comment by phillipc09** [comment]
Thanks for the setup advice...another quick and very newb question....Having an issue w/ babel loader....am I not installing the right webpack and/or correct version of babel-loader?  I've read that this could be a config issue..
ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-loader' in C:\Users\phill\pxy\examples\plotly
 @ multi main
