### ISSUE TITLE
Error: Module not found: Error: Cannot resolve module 'react-dom'

### ISSUE THREAD

**Issue by phillipc09** [stitchfix/pyxley#38]
Hi, after executing `$ npm init pyxapp` and `npm install`, I'm coming across a couple other errors:

 `ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'react-dom' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:99-119

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'd3' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:120-133

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'metrics-graphics' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:0-27

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'plotly.js' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:0-20

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'jquery' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:0-17

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'datamaps' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:0-19

ERROR in C:/Users/phill/pxy/~/pyxley/build/pyxley.js
Module not found: Error: Cannot resolve module 'nvd3' in C:\Users\phill\pxy\node_modules\pyxley\build
 @ C:/Users/phill/pxy/~/pyxley/build/pyxley.js 1:0-15`

What am I doing wrong here?  I checked and my react-dom is version 0.14.7

**Comment by nmkridler** [comment]
I'm not sure, I haven't had a chance to play with it on windows yet. I'll try to take a look soon.

**Comment by cone001** [comment]
@nmkridler , is there a good way to play pyxley on Windows? I have came across some problems and don't know where to turn to.
