### ISSUE TITLE
How long does it take to boot up?

### ISSUE THREAD

**Issue by springcoil** [stitchfix/pyxley#4]
Hi all,
I'm working through the examples, running python 2.7 (it seems python 3.4 doesn't work).

However I just get this - and a blank page. 

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [19/Jul/2015 14:31:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2015 14:31:09] "GET /static/bower_components/topojson/topojson.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2015 14:31:09] "GET /static/bower_components/datamaps/dist/datamaps.usa.min.js HTTP/1.1" 200 -

**Comment by nmkridler** [comment]
When you check your browser console, does it have any problem loading the resources? Not sure why it shows a blank page.

**Comment by springcoil** [comment]
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/datatables/media/css/jquery.dataTables.min.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/metrics-graphics/dist/metricsgraphics.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/datatables/media/js/jquery.dataTables.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/d3/d3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/require/build/require.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/react-bootstrap/react-bootstrap.min.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/layout.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/metrics-graphics/dist/metricsgraphics.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/react/react.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/pyxley/build/pyxley.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /static/bower_components/pyxley/build/pyxley.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:13] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/Jul/2015 17:47:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:14] "GET /static/bower_components/react/react.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2015 17:47:14] "GET /static/bower_components/datatables/media/js/jquery.dataTables.js HTTP/1.1" 200 -

**Comment by springcoil** [comment]
Using Safari on Mac OS X

**Comment by nmkridler** [comment]
@springcoil there seems to have been an issue with the jinja template writing out bools incorrectly. This would also cause a blank page. I pushed a new version. Try it out and let me know if it works.

**Comment by springcoil** [comment]
Hi Nick,
Cool I will check that later :)
Nick I am also planning to give an intro to this at a Meetup in Luxembourg
in Europe sometime in a few months.

On Sun, Jul 26, 2015 at 11:55 PM, Nick Kridler <notifications@github.com>
wrote:

> @springcoil <https://github.com/springcoil> there seems to have been an
> issue with the jinja template writing out bools incorrectly. This would
> also cause a blank page. I pushed a new version. Try it out and let me know
> if it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stitchfix/pyxley/issues/4#issuecomment-125043672>.
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
Hi @nmkridler they all work now with Python 2.7 except the DataTables example

**Comment by nmkridler** [comment]
@springcoil I found the issue, in layout.js the type isn't being cast as a string.
