### ISSUE TITLE
Example Wrong!!!!

### ISSUE THREAD

**Issue by qichaotang** [stitchfix/pyxley#48]
python app.py

> PyxleyApp@0.0.1 build /home/yujingmin/pyxley-master/examples/custom_react
> webpack

Hash: 829dbf17cef235e992a5
Version: webpack 1.14.0
Time: 3006ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.49 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
    + 460 hidden modules

ERROR in ./project/static/jsx/custom.js
Module not found: Error: Cannot resolve module 'pyxley' in /home/yujingmin/pyxley-master/examples/custom_react/project/static/jsx
 @ ./project/static/jsx/custom.js 16:14-31
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat

> PyxleyApp@0.0.1 build /home/yujingmin/pyxley-master/examples/custom_react
> webpack

Hash: 65f4d854c69451f4a3f7
Version: webpack 1.14.0
Time: 2888ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.49 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
    + 460 hidden modules

ERROR in ./project/static/jsx/custom.js
Module not found: Error: Cannot resolve module 'pyxley' in /home/yujingmin/pyxley-master/examples/custom_react/project/static/jsx
 @ ./project/static/jsx/custom.js 16:14-31
 * Debugger is active!
 * Debugger pin code: 121-055-446

**Comment by qichaotang** [comment]
I need help!!!

**Comment by nmkridler** [comment]
it looks like, the pyxley javascript library was left out of package.json. You can steal one of the package.json files from the other examples or just do an `npm install pyxley` then it should build. i'll update it when i get a chance

**Comment by nmkridler** [comment]
i updated the package.json, it should work
