### ISSUE TITLE
Example: metricsgraphics layout.js has incorrect value for boolean

### ISSUE THREAD

**Issue by harshnisar** [stitchfix/pyxley#8]
The static/layout.js file has True instead of true and False instead of false in line 5.

I thought I will make a pull request and even forked, but the layout.js file comes after the bower install  and hence I am not sure how I can fix it for the main repo.

If there is a way I can help, let me know, I will send a pull :)

**Comment by nmkridler** [comment]
I think the issue is with the jinja templating. I still need to write tests, but I'll try to add in a fix. I suspect, I just need to specify that it's a bool in the template. Out of curiosity, what system are you running on so I can see if I can replicate it. 

Thanks!

**Comment by nmkridler** [comment]
@harshnisar I was finally able to replicate this. I'm using json.dumps before the jinja template and it seems to have fixed the problem. Let me know if you know of a more elegant solution.

**Comment by harshnisar** [comment]
@nmkridler  Hey. Sorry I forgot about this issue. I am on a Windows 7 system using Python 2.7.9. 

Well to solve it myself I just edited the bool value manually. 
You can trace why the other bools in the same line come out correctly, but the last three don't.  (The problem was only in the last three bools in the chain)
